name: Build - support_prj_pstmt-git-action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Package JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract Commit Message
        run: |
          SAFE_COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | tr -cd '[:alnum:]_-')
          echo "COMMIT_MSG=$SAFE_COMMIT_MSG"
          echo "COMMIT_MSG=$SAFE_COMMIT_MSG" >> $GITHUB_ENV

      - name: Generate Timestamp
        run: echo "BUILD_TIMESTAMP=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Debug Timestamp
        run: |
          echo "Generated Timestamp: ${{ env.BUILD_TIMESTAMP }}"

      - name: Print Build Metadata
        run: |
          echo "App Name: support_prj_pstmt-git-action"
          echo "Build Time (UTC): ${{ env.BUILD_TIMESTAMP }}"
          echo "Branch: ${{ github.ref }}"
          echo "Triggered by: ${{ github.actor }}"

      - name: Build with Maven
        run: mvn clean package -Dcommit.message=${{ env.COMMIT_MSG }}

      - name: List JAR Output
        run: ls -lh target/*.jar

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: support-jar-${{ env.COMMIT_MSG }}
          path: target/*.jar
